### ISSUE TITLE
Can contact unidentified crowds before detected

### ISSUE THREAD

**Issue by Stifling-Bossness** [DrCarlLuo/RimworldMod_RaidAlarm-PreemptiveStrike#12]
Using comms consoles, you can communicate with unidentified crowds before they're even detected.

![](https://i.imgur.com/KQHFkpD.png)
![](https://i.imgur.com/sSTT1Oq.png)

In this example, I'm able to attempt to establish contact with crowds before they're detected by either colony. Viewing the world map does not reveal any incoming crowds on either colony.

This could also be a completely different issue of being able to contact a crowd after their dissipation, but I find that less likely.

**Comment by DrCarlLuo** [comment]
Thank you for letting me know this. I will fix it asap

**Comment by Stifling-Bossness** [comment]
Should be fixed in 1.1.5
