### ISSUE TITLE
Application of Japanese translation to workshops

### ISSUE THREAD

**Issue by Proxyer** [DrCarlLuo/RimworldMod_RaidAlarm-PreemptiveStrike#16]
Hello DrCarlLuo.
Would you please apply the Japanese translation I provided and merged to the workshop? Thank you.

**Comment by DrCarlLuo** [comment]
Hi Proxyer!
I've just uploaded it to steam workshop. Sorry for uploading it this late. I've been really busy and keeping forgetting important things around these days. And thank you again for your amazing Japanese translation!
