### ISSUE TITLE
Intent revealed on icons before discovered

### ISSUE THREAD

**Issue by Stifling-Bossness** [DrCarlLuo/RimworldMod_RaidAlarm-PreemptiveStrike#4]
I've noticed that sometimes the intent of a crowd is revealed via their icon before it's actually listed in the report.

Example:
 ![](https://i.imgur.com/GsJntNT.png)

In this example, they're revealed to be traders before their intention is actually "discovered". The faction in question is from another mod (Sparking Worlds, I think) but it also happens with vanilla factions.

Some possible solutions would be to either keep the icon obscured or maybe just display a general "friendly" icon and switch to the trader icon when intention is revealed.

Tested on 1.0 and 1.1, both versions have the same issue.

**Comment by DrCarlLuo** [comment]
Thank you very much for letting me know this! :) I'll fix it soon.

**Comment by Stifling-Bossness** [comment]
Resolved in 1.1.3
