### ISSUE TITLE
Resource Pods confirmation typo

### ISSUE THREAD

**Issue by Stifling-Bossness** [DrCarlLuo/RimworldMod_RaidAlarm-PreemptiveStrike#5]
![](https://i.imgur.com/km7GId5.png)

Should be "resource" not "resouce"

Kind of confused me at first, I thought it was "rescue" and sent someone out to the landing spot ahead of time, only to find out it was a muffalo meat drop :(

**Comment by DrCarlLuo** [comment]
Hah, sorry for this frustrating typo. But, I think you did manage to "rescue" all of that muffalo meat from rotting. XD 
I will fix this typo asap.

**Comment by Stifling-Bossness** [comment]
Should be fixed with #8 unless I'm completely blind and missed it when I went through.
